// Nancy Tours Costa Rica — Tours data (single source of truth)
// =====================================================================
// Used by tour-detail.js. Add new tours here as objects keyed by slug.
// 'default' is the fallback shown when ?id= doesn't match.

window.TOURS = {
  'chirripo': {
    title: 'Cerro Chirripó',
    loc: 'Pérez Zeledón · Talamanca',
    elev: '3.820 m',
    tag: 'AVENTURA · 3 DÍAS',
    hero: 'img/chirripo-summit.jpg',
    nextDate: '13 — 15 jun · vie a dom',
    duration: '3 días · 2 noches',
    diff: 'Alta',
    cupo: '6 / 10',
    minAge: '14 años',
    price: '$340',
    lead: 'El techo de Costa Rica. Tres días de caminata por el Parque Nacional Chirripó, refugio Crestones la noche del segundo día, cumbre al amanecer. Una de las experiencias más bonitas e intensas del país — y lo hacés acompañada todo el camino.',
    blurb: 'El Chirripó no se sube de un solo tirón. Llegamos a San Gerardo el viernes en la tarde, dormimos en cabinas locales, arrancamos antes del amanecer. El primer día son 14 km hasta el refugio Crestones. El segundo día subimos a la cumbre al amanecer y bajamos. El tercero regresamos a Heredia. Llevo radios, GPS, botiquín de zona remota y un plan B para cada tramo. No improviso. Y aún así, queda tiempo para mirar las lagunas, sacar fotos y dormirse al final del día con una sonrisa.',
    itinerary: [
      { d: 'DÍA 1 · Viernes', items: ['6 AM salida desde Heredia', '11 AM almuerzo en San Isidro de El General', '2 PM check-in cabinas en San Gerardo', '4 PM charla técnica + revisión de equipo', 'Cena temprana, dormir 9 PM'] },
      { d: 'DÍA 2 · Sábado', items: ['3 AM desayuno + salida al puesto de control', '5 AM iniciamos ascenso (14 km, ~9 hrs)', '2 PM llegada al Refugio Base Crestones', '4 PM caminata corta a Las Morrenas (opcional)', 'Cena en refugio, dormir 8 PM'] },
      { d: 'DÍA 3 · Domingo', items: ['3 AM desayuno + ascenso a la cumbre', '5 AM cumbre — amanecer 3.820 m', '7 AM regreso al refugio, empacar', '8 AM bajada (14 km, ~6 hrs)', '4 PM regreso a Heredia llegando ~9 PM'] },
    ],
    incl: ['Transporte ida y vuelta desde Heredia', 'Cabinas en San Gerardo (2 noches en refugio)', 'Desayunos, almuerzos y cenas del tour', 'Guía profesional (Nancy)', 'Radios + GPS + botiquín', 'Permisos del parque (SINAC)'],
    excl: ['Bebidas alcohólicas', 'Bastones de trekking (alquiler $5/día)', 'Propinas a personal del refugio', 'Seguro de viaje (recomendado)'],
    bring: ['Botas de montaña ya probadas', 'Mochila 40-50 L', 'Saco de dormir < 0°C', 'Capa de lluvia obligatoria', 'Ropa térmica primera capa', 'Linterna frontal + baterías', 'Cantimplora 2 L mínimo', 'Bloqueador solar SPF 50+', 'Cédula o pasaporte'],
    faq: [
      ['¿Cuánta condición física se necesita?', 'Buena. Es una caminata exigente — recomiendo entrenar 1-2 meses antes con caminatas largas. No se necesita ser maratonista, pero sí caminante regular.'],
      ['¿Hay riesgo de mal de altura?', 'Algunas personas lo sienten leve sobre 3.000 m. Yo manejo el ritmo del grupo para minimizarlo. Si alguien se siente mal en serio, descendemos.'],
      ['¿Qué pasa si llueve mucho?', 'Subimos igual con equipo de lluvia. Solo cancelo si SINAC cierra el parque o hay alerta seria — en ese caso reembolso completo o reagendamos.'],
    ],
    related: ['bajos-toro', 'cavernas-venado', 'tortuguero'],
  },
  'bajos-toro': {
    title: 'Bajos del Toro',
    loc: 'Alajuela · Bosque nuboso',
    elev: '1.400 m',
    tag: 'DÍA COMPLETO',
    hero: 'img/waterfall.jpg',
    nextDate: '14 jun · sábado',
    duration: '1 día',
    diff: 'Media',
    cupo: '4 / 12',
    minAge: '12 años',
    price: '$85',
    lead: 'Una de las cataratas más fotogénicas del país, escondida en un cañón verde profundo. Caminata descendente con cuerdas en los tramos finales — vale cada paso.',
    blurb: 'Salimos temprano de Heredia, llegamos a la entrada del sendero como a las 8 AM. El descenso es de 1.5 km con cuerdas en los tramos verticales — no es técnico, pero requiere brazo y zapato cerrado. Abajo hay tiempo para nadar (¡el agua está fría!), sacar fotos, almorzar en el restaurante de la familia que mantiene el sendero. Volvemos antes de que oscurezca.',
    itinerary: [
      { d: 'MAÑANA', items: ['6 AM salida desde Heredia centro', '8 AM llegada al sendero', '8:30 AM inicio del descenso (1.5 km)', '10 AM llegada a la catarata + tiempo libre'] },
      { d: 'MEDIODÍA', items: ['12 PM almuerzo típico en restaurante local', '1:30 PM regreso al sendero', '3 PM ascenso al punto de salida'] },
      { d: 'TARDE', items: ['4 PM parada en mirador del valle', '6 PM regreso a Heredia'] },
    ],
    incl: ['Transporte ida y vuelta', 'Almuerzo típico', 'Guía profesional', 'Cuerdas y arnés', 'Entrada al sendero'],
    excl: ['Equipo personal (mochila, ropa)', 'Bebidas extra', 'Propinas'],
    bring: ['Zapato cerrado con buena tracción', 'Ropa de cambio (te vas a mojar)', 'Capa de lluvia', 'Bloqueador + repelente', 'Bolsa para basura propia'],
    faq: [
      ['¿Qué tan difícil es el descenso?', 'Es media. Hay cuerdas pero no se necesita experiencia previa — te explico todo antes. Si no estás cómoda con las cuerdas, podés esperar arriba.'],
      ['¿Se puede ir con niños?', 'Desde 12 años con buena condición. Más chicos no, las cuerdas requieren brazo.'],
    ],
    related: ['chirripo', 'cavernas-venado', 'ballenas-uvita'],
  },
  'tortuguero': {
    title: 'Tortuguero',
    loc: 'Limón · Caribe Norte',
    elev: 'Nivel del mar',
    tag: '2 DÍAS · 1 NOCHE',
    hero: 'img/boat-tour.jpg',
    nextDate: '21 — 22 jun · sáb-dom',
    duration: '2 días · 1 noche',
    diff: 'Baja',
    cupo: '2 / 14',
    minAge: 'Sin límite',
    price: '$220',
    lead: 'Canales caribeños, fauna abundante, lancha y lodge sencillo. El tour perfecto para tercera edad o familias — no se camina mucho, se mira y se respira.',
    blurb: 'Salimos sábado temprano de Heredia, transbordamos en La Pavona a la lancha que nos lleva al pueblo. Lodge sencillo pero limpio frente al canal. Tour de canales en la tarde (caimanes, monos, pájaros), cena tipica caribeña. Domingo en la mañana otra ronda de canales y caminata corta por el sendero del Cerro. Regresamos a Heredia llegando antes de noche.',
    itinerary: [
      { d: 'DÍA 1 · Sábado', items: ['5 AM salida Heredia', '10 AM transbordo a lancha en La Pavona', '12 PM llegada al lodge + almuerzo', '3 PM tour de canales en lancha', '7 PM cena caribeña'] },
      { d: 'DÍA 2 · Domingo', items: ['5:30 AM tour de canales al amanecer (mejor fauna)', '8 AM desayuno', '10 AM caminata sendero Cerro Tortuguero', '12 PM almuerzo + checkout', '2 PM regreso a Heredia llegando ~7 PM'] },
    ],
    incl: ['Transporte completo (bus + lancha)', 'Una noche en lodge', '4 comidas', 'Dos tours de canales', 'Guía + propinas básicas'],
    excl: ['Bebidas alcohólicas', 'Tour nocturno opcional ($15)', 'Tour de tortugas en temporada ($30)'],
    bring: ['Repelente fuerte (mucho mosquito)', 'Bloqueador SPF 50', 'Ropa ligera + capa de lluvia', 'Zapato cómodo'],
    faq: [
      ['¿Es bueno para tercera edad?', 'Excelente. Casi no se camina. Las lanchas tienen sombra y el lodge es de un solo piso.'],
      ['¿Se ven tortugas?', 'En temporada (julio-octubre) sí, con tour adicional nocturno. Fuera de temporada vemos los nidos vacíos pero no el desove.'],
    ],
    related: ['ballenas-uvita', 'chirripo', 'bajos-toro'],
  },
  'cavernas-venado': {
    title: 'Cavernas de Venado',
    loc: 'San Carlos · Alajuela',
    elev: '300 m',
    tag: 'DÍA COMPLETO',
    hero: 'img/cave.jpg',
    nextDate: '28 jun · sábado',
    duration: '1 día',
    diff: 'Media',
    cupo: '8 / 12',
    minAge: '8 años',
    price: '$95',
    lead: 'Un sistema de cuevas calizas con estalactitas, estalagmitas y un río subterráneo. Cuatro horas adentro de la tierra, con casco, linterna y guía local.',
    blurb: 'Salimos temprano hacia San Carlos. La entrada a la caverna tiene un río que se cruza, después el sistema interior tiene tramos angostos y pasajes con agua hasta la cintura. No es claustrofóbica si no te encerrás — siempre hay luz del guía adelante. Llevamos casco, linterna y arnés. La caminata afuera es de 30 minutos por sendero llano. Volvemos en la tarde con almuerzo típico en familia local.',
    itinerary: [
      { d: 'MAÑANA', items: ['6 AM salida desde Heredia', '9 AM llegada y registro', '10 AM ingreso a la caverna (4 horas)'] },
      { d: 'TARDE', items: ['2 PM almuerzo típico', '3:30 PM regreso a Heredia', '6 PM llegada estimada'] },
    ],
    incl: ['Transporte ida y vuelta', 'Almuerzo típico', 'Casco, linterna y arnés', 'Guía local certificado', 'Entrada al sistema'],
    excl: ['Ropa de cambio personal', 'Bebidas extra'],
    bring: ['Zapato cerrado con buena tracción', 'Ropa que se pueda mojar (hasta cintura)', 'Cambio completo de ropa y zapato', 'Bolsa estanca para celular'],
    faq: [
      ['¿Es peligroso?', 'No, es un recorrido turístico bien establecido. El guía local conoce la cueva al detalle. Hay tramos angostos pero no técnicos.'],
      ['¿Y si soy claustrofóbico?', 'Mejor no. El último tramo es estrecho durante unos 20 metros. Te recomiendo el tour de Bajos del Toro como alternativa.'],
    ],
    related: ['bajos-toro', 'chirripo', 'tortuguero'],
  },
  'ballenas-uvita': {
    title: 'Ballenas en Uvita',
    loc: 'Uvita · Pacífico Sur',
    elev: 'Nivel del mar',
    tag: 'TEMPORADA',
    hero: 'img/whale.jpg',
    nextDate: '12 jul · sábado',
    duration: '1 día',
    diff: 'Baja',
    cupo: '10 / 16',
    minAge: 'Sin límite',
    price: '$110',
    lead: 'Avistamiento de ballenas jorobadas en el Parque Marino Ballena. Solo en temporada (julio-octubre). Lancha, biólogo a bordo, almuerzo en la playa.',
    blurb: 'Las jorobadas migran de la Antártida a parir en aguas tibias de Costa Rica. De julio a octubre las vemos cerca de la costa de Uvita, sobre todo con sus crías recién nacidas. La salida es en lancha grande con biólogo del parque a bordo — no es solo "ver y volver", se explica el comportamiento, los cantos, las rutas migratorias. Después almuerzo en la playa, tiempo libre y regreso.',
    itinerary: [
      { d: 'MAÑANA', items: ['4 AM salida desde Heredia (es lejos)', '8 AM llegada a Uvita + desayuno', '9 AM salida en lancha (3 hrs)'] },
      { d: 'TARDE', items: ['12 PM almuerzo en playa', '2 PM tiempo libre / playa', '4 PM regreso, llegada a Heredia ~8 PM'] },
    ],
    incl: ['Transporte ida y vuelta', 'Desayuno + almuerzo', 'Lancha con biólogo del parque', 'Entrada al Parque Marino Ballena', 'Chalecos salvavidas'],
    excl: ['Bebidas alcohólicas', 'Compras personales'],
    bring: ['Bloqueador SPF 50 reef-safe', 'Sombrero + lentes de sol', 'Capa de lluvia ligera', 'Cámara o celular con bolsa estanca', 'Medicación para mareo si sufrís en lancha'],
    faq: [
      ['¿Garantizan ver ballenas?', 'No 100% pero en temporada las vemos en el 90% de las salidas. Si no se ven, te ofrecemos otra salida sin costo en otra fecha.'],
      ['¿Bueno para niños?', 'Sí, las lanchas tienen sombra y son estables. Niños desde 4 años suelen disfrutar mucho.'],
    ],
    related: ['tortuguero', 'bajos-toro', 'chirripo'],
  },
  'volcan-barva': {
    title: 'Volcán Barva',
    loc: 'Heredia · Parque Nacional Braulio Carrillo',
    elev: '2.906 m',
    tag: 'AVENTURA · DÍA',
    hero: 'img/foggy-bridge.jpg',
    nextDate: '05 jul · domingo',
    duration: '1 día',
    diff: 'Media',
    cupo: '8 / 12',
    minAge: '12 años',
    price: '$75',
    lead: 'El volcán de mi infancia. Caminata de bosque nuboso hasta la laguna del cráter, a media hora de Heredia.',
    blurb: 'Este es el tour que más amo dar — me lleva a los senderos donde caminaba con mi papá. El Barva es un volcán dormido, su laguna del cráter es un espejo verde rodeado de bosque nuboso. La caminata es de 4 km hasta la laguna, con tramos empinados pero sin tecnicismos. El bosque tiene quetzales, monos cara blanca y mucha vegetación endémica. Lluvia casi garantizada, capa obligatoria.',
    itinerary: [
      { d: 'MAÑANA', items: ['7 AM salida desde Heredia centro', '8:30 AM llegada al puesto Barva (SINAC)', '9 AM inicio del sendero (4 km, 2.5 hrs)'] },
      { d: 'MEDIODÍA', items: ['11:30 AM llegada a la laguna del cráter', '12 PM almuerzo (sándwich + fruta)', '1 PM regreso por el sendero'] },
      { d: 'TARDE', items: ['3 PM regreso al puesto', '4 PM llegada a Heredia'] },
    ],
    incl: ['Transporte desde Heredia', 'Entrada al parque (SINAC)', 'Almuerzo ligero', 'Guía profesional', 'Capa de lluvia de cortesía'],
    excl: ['Bebidas extra', 'Equipo personal'],
    bring: ['Botas con buena tracción', 'Capa de lluvia personal (de respaldo)', 'Suéter o capa térmica', 'Repelente + bloqueador', 'Cámara'],
    faq: [
      ['¿Va a llover?', 'Casi seguro. Es bosque nuboso. Pero es lluvia ligera y la capa lo resuelve.'],
      ['¿Veré quetzales?', 'En temporada (oct-abr) hay buena chance. Fuera de temporada es más raro pero pasa.'],
    ],
    related: ['chirripo', 'bajos-toro', 'cerro-chompipe'],
  },
  'cerro-chompipe': {
    title: 'Cerro Chompipe',
    loc: 'San Rafael de Heredia',
    elev: '2.250 m',
    tag: 'AVENTURA · DÍA',
    hero: 'img/hiking-trail.jpg',
    nextDate: '22 jun · domingo',
    duration: '1 día',
    diff: 'Media',
    cupo: '10 / 12',
    minAge: '12 años',
    price: '$60',
    lead: 'Caminata corta pero empinada al mirador del Cerro Chompipe, con vista al Valle Central completo en día claro.',
    blurb: 'Es el "Chirripó chiquitito" del Valle Central. Salida desde San Rafael, sendero de 3 km de subida constante por bosque secundario, llegada a una explanada con vista panorámica del valle y los volcanes circundantes. En días claros se ve hasta el Pacífico. Salida temprano para esquivar la neblina de la tarde.',
    itinerary: [
      { d: 'MAÑANA', items: ['6 AM salida Heredia centro', '7 AM llegada al inicio del sendero', '7:30 AM ascenso (3 km, 2 hrs)'] },
      { d: 'MEDIODÍA', items: ['10 AM cumbre + desayuno con vista', '11 AM regreso por mismo sendero', '1 PM regreso a Heredia'] },
    ],
    incl: ['Transporte desde Heredia', 'Desayuno con vista', 'Guía profesional', 'Bastones si se requieren'],
    excl: ['Almuerzo (volvemos antes)', 'Equipo personal'],
    bring: ['Zapato con tracción', 'Capa de lluvia', 'Botella de agua 1 L', 'Bloqueador + sombrero'],
    faq: [
      ['¿Bueno para entrenar al Chirripó?', '¡Excelente! Es la rutina que recomiendo a los que van a subir Chirripó después.'],
    ],
    related: ['volcan-barva', 'chirripo', 'bajos-toro'],
  },
  'volcan-poas': {
    title: 'Volcán Poás',
    loc: 'Alajuela · cráter activo',
    elev: '2.708 m',
    tag: 'DÍA',
    hero: 'img/chirripo-sign.jpg',
    nextDate: '20 jul · domingo',
    duration: '1 día',
    diff: 'Baja',
    cupo: '14 / 16',
    minAge: 'Sin límite',
    price: '$70',
    lead: 'Uno de los cráteres activos más impresionantes del mundo. Sendero corto, mirador con barandas, perfecto para todas las edades.',
    blurb: 'El Poás es la postal volcánica de Costa Rica. Cráter activo de 1.3 km de diámetro con una laguna verde-azul de azufre, vapor visible casi todos los días. La caminata es corta — 800 metros desde el centro de visitantes al mirador. Apto para tercera edad, niños, capacidades reducidas (sendero pavimentado). Solo hay que coordinar bien el horario porque las nubes suben temprano.',
    itinerary: [
      { d: 'MAÑANA', items: ['6 AM salida Heredia (temprano por la neblina)', '8 AM llegada al parque', '8:30 AM caminata al mirador del cráter (15 min)'] },
      { d: 'MEDIODÍA', items: ['10 AM senderos cortos del bosque', '12 PM almuerzo en restaurante local', '2 PM regreso a Heredia'] },
    ],
    incl: ['Transporte ida y vuelta', 'Entrada al Parque Nacional Volcán Poás', 'Almuerzo típico', 'Guía profesional', 'Casco (obligatorio para visitar el cráter)'],
    excl: ['Bebidas extra', 'Souvenirs en la tienda del parque'],
    bring: ['Suéter (puede hacer frío)', 'Capa de lluvia ligera', 'Bloqueador (UV alto)', 'Cámara'],
    faq: [
      ['¿Apto para personas mayores?', 'Sí, es uno de los tours más accesibles. Sendero pavimentado, distancia corta, sin desnivel.'],
      ['¿Se ve el cráter o pueden cerrarlo?', 'En clima inestable a veces SINAC restringe la visita al mirador. Si pasa, te avisamos antes y reagendamos.'],
    ],
    related: ['bajos-toro', 'cavernas-venado', 'chirripo'],
  },
  'corcovado': {
    title: 'Corcovado',
    loc: 'Península de Osa · Pacífico Sur',
    elev: 'Variable · selva primaria',
    tag: 'AVENTURA · 3 DÍAS',
    hero: 'img/tortuguero-group.jpg',
    nextDate: '09 — 11 ago · sáb-lun',
    duration: '3 días · 2 noches',
    diff: 'Alta',
    cupo: '4 / 10',
    minAge: '16 años',
    price: '$480',
    lead: 'La selva primaria más densa de Centroamérica, según National Geographic. Tres días en Corcovado con guías locales, cabinas rústicas y rutas a Sirena.',
    blurb: 'Corcovado no es un tour, es una expedición. Acceso solo por lancha o caminata desde Carate. Pernoctamos en estación biológica Sirena, dormimos con sonidos de monos congos, despertamos con tucanes. Hay tapires, dantas, jaguares (raros pero pasa). Los senderos son de selva primaria pesada — calor, humedad, lluvia. No es para todos. Es para los que quieren ver Costa Rica salvaje sin filtros.',
    itinerary: [
      { d: 'DÍA 1 · Sábado', items: ['5 AM salida Heredia hacia Sierpe', '12 PM almuerzo + transbordo a lancha', '3 PM llegada a estación Sirena', '5 PM caminata nocturna corta'] },
      { d: 'DÍA 2 · Domingo', items: ['5 AM caminata por senderos primarios (6 hrs)', '12 PM almuerzo en estación', '3 PM segunda caminata corta', '7 PM cena + observación nocturna'] },
      { d: 'DÍA 3 · Lunes', items: ['6 AM última caminata + desayuno', '10 AM checkout y lancha de regreso', '1 PM almuerzo en Sierpe', '8 PM llegada a Heredia'] },
    ],
    incl: ['Transporte completo (bus + lancha)', '2 noches en estación Sirena', 'Todas las comidas', 'Guía local certificado (SINAC)', 'Permisos del parque'],
    excl: ['Equipo personal de senderismo', 'Tour opcional de delfines ($40)', 'Bebidas alcohólicas'],
    bring: ['Botas de selva (no botas de montaña)', 'Repelente fuerte (mucho mosquito)', 'Ropa ligera de secado rápido x3', 'Capa de lluvia', 'Linterna frontal + baterías', 'Bloqueador biodegradable'],
    faq: [
      ['¿Veré jaguar?', 'Probablemente no. Son extremadamente esquivos. Tapires y monos sí, casi seguro.'],
      ['¿Qué tan difícil?', 'Alta — calor, humedad, terreno irregular, distancias largas. Requiere buena condición.'],
      ['¿Y la malaria?', 'No hay malaria en Costa Rica. Sí mosquitos comunes — repelente y manga larga al atardecer.'],
    ],
    related: ['chirripo', 'tortuguero', 'ballenas-uvita'],
  },
  'puentes-colgantes': {
    title: 'Puentes Colgantes',
    loc: 'Monteverde · bosque nuboso',
    elev: '1.500 m',
    tag: 'TERCERA EDAD',
    hero: 'img/foggy-bridge.jpg',
    nextDate: '06 jul · domingo',
    duration: '1 día',
    diff: 'Baja',
    cupo: '12 / 16',
    minAge: 'Sin límite',
    price: '$95',
    lead: 'Recorrido por seis puentes colgantes sobre el dosel del bosque nuboso de Monteverde. Ritmo suave, ideal para tercera edad y familias.',
    blurb: 'Monteverde es uno de los bosques nubosos más famosos del mundo. El circuito de puentes te lleva al nivel del dosel sin tener que escalar — caminás por puentes colgantes de hasta 50 metros de altura. Las vistas son únicas: ves los árboles desde arriba, observás aves a tu altura. Sendero pavimentado en los primeros tramos, terreno suave en los siguientes. Apto para abuelos con buena movilidad.',
    itinerary: [
      { d: 'MAÑANA', items: ['6 AM salida Heredia (3 hrs de viaje)', '9 AM llegada a Monteverde', '10 AM circuito de puentes (3 hrs, ritmo suave)'] },
      { d: 'MEDIODÍA', items: ['1 PM almuerzo típico en Santa Elena', '3 PM tiempo libre en pueblo', '4 PM regreso a Heredia (7 PM llegada)'] },
    ],
    incl: ['Transporte ida y vuelta', 'Entrada al sendero de puentes', 'Almuerzo típico', 'Guía profesional', 'Bastones si requeridos'],
    excl: ['Compras en tiendas locales', 'Otros tours en la zona'],
    bring: ['Capa de lluvia (siempre)', 'Zapato cerrado cómodo', 'Cámara con zoom para aves', 'Suéter ligero'],
    faq: [
      ['¿Apto para personas con miedo a las alturas?', 'Los puentes se mecen un poco pero las barandas son altas. Algunos los hacen sin problema, otros eligen rodear por el sendero alterno.'],
      ['¿Cuánto se camina en total?', 'Unos 3 km en 3 horas, ritmo suave con pausas.'],
    ],
    related: ['volcan-poas', 'volcan-barva', 'bajos-toro'],
  },
  'sarchi-grecia': {
    title: 'Sarchí + Grecia',
    loc: 'Alajuela · pueblos tradicionales',
    elev: '1.000 m',
    tag: 'CULTURAL',
    hero: 'img/chirripo-sign.jpg',
    nextDate: '13 jul · domingo',
    duration: '1 día',
    diff: 'Baja',
    cupo: '10 / 16',
    minAge: 'Sin límite',
    price: '$65',
    lead: 'Dos pueblos tradicionales del Valle Central: Sarchí con sus talleres de carretas pintadas (patrimonio nacional) y Grecia con su iglesia de hierro centenaria.',
    blurb: 'Tour cultural sin caminata. Empezamos en Sarchí visitando los talleres familiares de carretas — pintura tradicional, todavía hecha a mano por las familias originarias. Demostración en vivo. Almuerzo en restaurante típico con sopa negra y picadillo. Tarde en Grecia para ver la famosa iglesia metálica importada de Bélgica en 1897 y armada con clavos en el parque central.',
    itinerary: [
      { d: 'MAÑANA', items: ['8 AM salida Heredia', '9 AM llegada a Sarchí', '9:30 AM talleres de carretas + demostración', '12 PM almuerzo típico'] },
      { d: 'TARDE', items: ['2 PM Grecia · iglesia metálica + parque', '3:30 PM mercado artesanal', '5 PM regreso a Heredia (6 PM llegada)'] },
    ],
    incl: ['Transporte', 'Almuerzo típico', 'Guía cultural', 'Entradas a museos'],
    excl: ['Compras de artesanía', 'Souvenirs personales'],
    bring: ['Cámara', 'Efectivo para compras (artesanos no aceptan tarjeta)', 'Ropa cómoda casual'],
    faq: [
      ['¿Bueno para grupos con niños?', 'Sí, hay actividades para todas las edades. Los talleres permiten pintar una carreta chiquita de recuerdo.'],
    ],
    related: ['volcan-poas', 'mercados-sj', 'puentes-colgantes'],
  },
  'mercados-sj': {
    title: 'Mercados de San José',
    loc: 'Capital · gastronomía local',
    elev: 'Nivel ciudad',
    tag: 'CULTURAL',
    hero: 'img/boat-tour.jpg',
    nextDate: '27 jul · sábado',
    duration: '1 día',
    diff: 'Baja',
    cupo: '14 / 16',
    minAge: 'Sin límite',
    price: '$55',
    lead: 'Recorrido por los mercados emblemáticos de San José: Central, Borbón y Coca-Cola. Probamos frutas, cafés, sodas tradicionales — la capital sin filtros.',
    blurb: 'San José no es un destino turístico obvio, pero los mercados son una experiencia única. Empezamos en el Mercado Central (1880) con sus sodas, pescaderías y carnicerías históricas. Probamos copos, churchills, batidos de cas. Después al Borbón para ver el lado más popular y a la Coca-Cola para conocer la terminal de bus a Limón. Almuerzo en una soda emblemática. Tour caminado, ~3 km en total.',
    itinerary: [
      { d: 'MAÑANA', items: ['8 AM tren a San José desde Heredia', '9 AM Mercado Central (2 hrs)', '11 AM Mercado Borbón'] },
      { d: 'MEDIODÍA', items: ['12 PM almuerzo en soda histórica', '2 PM Mercado Coca-Cola', '4 PM tren de regreso a Heredia'] },
    ],
    incl: ['Tren ida y vuelta', 'Almuerzo en soda típica', 'Degustaciones en los mercados', 'Guía cultural'],
    excl: ['Compras personales', 'Bebidas extra'],
    bring: ['Efectivo (mercados casi no aceptan tarjeta)', 'Zapato cómodo de caminar', 'Cámara discreta'],
    faq: [
      ['¿Es seguro?', 'Sí, vamos en grupo y conozco bien las zonas. Llevá lo justo y andá pendiente como en cualquier mercado del mundo.'],
      ['¿Bueno para vegetarianos?', '¡Sí! Hay sodas con muchas opciones de gallo pinto, arroz con palmito, ensaladas de aguacate.'],
    ],
    related: ['sarchi-grecia', 'volcan-poas', 'puentes-colgantes'],
  },
  'a-medida': {
    title: 'Tu propio tour',
    loc: 'A donde vos quieras ir',
    elev: 'A elección',
    tag: 'A MEDIDA',
    hero: 'img/chirripo-lakes.jpg',
    nextDate: 'Coordiná fecha conmigo',
    duration: 'A elección',
    diff: 'A elección',
    cupo: 'Privado',
    minAge: 'A elección',
    price: 'Consultá',
    lead: 'Tours privados para grupos de 2 a 20 personas. Empresariales, cumpleaños, escuelas, despedidas. Decime qué tenés ganas de hacer y armo el plan.',
    blurb: 'Esto es lo más bonito de mi trabajo: armar el tour exacto que tu grupo necesita. Familias multigeneracionales con abuelos y nietos. Empresas que quieren team-building real (no encerrados en un hotel). Escuelas que quieren conectar a los estudiantes con la naturaleza. Cumpleaños con caminata + almuerzo en una catarata. Bodas con sesión de fotos en Chirripó. Lo que se te ocurra, lo planifico en menos de 48 horas con cotización clara.',
    itinerary: [],
    incl: ['Planificación detallada según tu grupo', 'Transporte coordinado', 'Logística completa', 'Guía profesional (yo)'],
    excl: ['Depende del tour que armemos'],
    bring: ['Coordinamos cuando definamos la ruta'],
    faq: [
      ['¿Cuánto cuesta?', 'Depende mucho: distancia, duración, tamaño del grupo, comidas, alojamiento. Cotizo en 48 horas con todo desglosado.'],
      ['¿Mínimo de personas?', 'Desde 2 personas. Para 1 sola persona te puedo recomendar unirte a un tour abierto.'],
      ['¿Hasta dónde llegan?', 'Toda Costa Rica. Si es muy lejos sumamos el costo de transporte extra, pero he llevado grupos a Corcovado, Drake, La Fortuna, Manuel Antonio, etc.'],
    ],
    related: ['chirripo', 'bajos-toro', 'corcovado'],
  },
  'default': {
    title: 'Tour',
    loc: 'Costa Rica',
    elev: '—',
    tag: 'TOUR',
    hero: 'img/chirripo-lakes.jpg',
    nextDate: 'Próxima fecha pendiente',
    duration: '—',
    diff: '—',
    cupo: '—',
    minAge: '—',
    price: 'Consultá',
    lead: 'Información detallada del tour próximamente. Mientras tanto, hablemos por WhatsApp y te cuento.',
    blurb: 'Este tour está siendo actualizado. Contactame para más información o consultá el catálogo completo.',
    itinerary: [],
    incl: [],
    excl: [],
    bring: [],
    faq: [],
    related: ['chirripo', 'bajos-toro', 'tortuguero'],
  },
};
